In [ ]:
pip install pandas

:

In [ ]:
import pandas as pd

:

In [4]:
df = pd.read_csv("ventas_retail.csv")

df

,ciudad,categoria,vendedor,trimestre,monto,unidades,descuento
0,Mendoza,Deportes,Pedro Ruiz,Q2,14078,9,0.00
1,Tucumán,Electrónica,Pedro Ruiz,Q2,67768,17,0.10
2,Rosario,Alimentos,Pedro Ruiz,Q3,56047,9,0.15
3,Tucumán,Hogar,Lucía Paz,Q3,76626,9,0.00
4,Tucumán,Hogar,Pedro Ruiz,Q2,62660,1,0.15
...,...,...,...,...,...,...,...
495,Buenos Aires,Ropa,Ana Torres,Q2,77930,10,0.20
496,Rosario,Electrónica,Lucía Paz,Q2,33380,19,0.05
497,Buenos Aires,Electrónica,María López,Q3,31035,9,0.05
498,Buenos Aires,Deportes,Luis Gómez,Q2,35620,13,0.00
499,Buenos Aires,Hogar,Pedro Ruiz,Q2,122360,7,0.05

In [6]:
grupos = df.groupby("ciudad")
print(type(grupos))

<class 'pandas.api.typing.DataFrameGroupBy'>

In [10]:
grupos = df.groupby("ciudad")
df.groupby("ciudad")["monto"].sum()

ciudad
Buenos Aires    8855199
Córdoba         7198111
Mendoza         7706414
Rosario         7938539
Tucumán         7221605
Name: monto, dtype: int64

In [20]:
df_promedios = df.groupby("ciudad")["monto"].mean().round(1)
df_promedios

ciudad
Buenos Aires    81240.4
Córdoba         75769.6
Mendoza         68807.3
Rosario         87236.7
Tucumán         77651.7
Name: monto, dtype: float64

In [21]:
df.groupby("ciudad")["monto"].count()

ciudad
Buenos Aires    109
Córdoba          95
Mendoza         112
Rosario          91
Tucumán          93
Name: monto, dtype: int64

In [22]:
df.groupby(["ciudad", "categoria"])["monto"].sum()

ciudad        categoria
Buenos Aires  Alimentos      1876997
              Deportes       1372041
              Electrónica    1951331
              Hogar          1607118
              Ropa           2047712
Córdoba       Alimentos      1787767
              Deportes       1778075
              Electrónica    1286509
              Hogar          1292147
              Ropa           1053613
Mendoza       Alimentos       891215
              Deportes       1718730
              Electrónica    1472067
              Hogar          1533021
              Ropa           2091381
Rosario       Alimentos      1715244
              Deportes       1676528
              Electrónica    1526021
              Hogar          1783981
              Ropa           1236765
Tucumán       Alimentos      2595971
              Deportes       1047502
              Electrónica    1445364
              Hogar          1324889
              Ropa            807879
Name: monto, dtype: int64

In [23]:
df.groupby("vendedor")["monto"].agg(["sum", "mean", "count","max"])

                   sum          mean  count     max
vendedor
Ana Torres     5592010  79885.857143     70  149832
Carlos Vera    5114603  75214.750000     68  145272
Clara Díaz     5051539  77715.984615     65  148273
Lucía Paz      4423650  77607.894737     57  145180
Luis Gómez     5188342  76299.147059     68  149701
María López    4380650  70655.645161     62  146398
Pedro Ruiz     4105135  78944.903846     52  146706
Sofía Herrera  5063939  87309.293103     58  149539

In [24]:
df.groupby("ciudad").agg(
    total_ventas   = ("monto",    "sum"),
    ticket_promedio= ("monto",    "mean"),
    unidades_total = ("unidades", "sum"),
    descuento_max  = ("descuento","max"),
)

              total_ventas  ticket_promedio  unidades_total  descuento_max
ciudad
Buenos Aires       8855199     81240.357798            1089            0.2
Córdoba            7198111     75769.589474             931            0.2
Mendoza            7706414     68807.267857            1175            0.2
Rosario            7938539     87236.692308             946            0.2
Tucumán            7221605     77651.666667             880            0.2